# Generated by Django 4.2.11 on 2025-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Фото товара')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
